# Generated by Django 5.2.6 on 2026-06-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GmailCredentials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(max_length=255, unique=True)),
                ("refresh_token", models.TextField()),
                (
                    "token_uri",
                    models.CharField(
                        default="https://oauth2.googleapis.com/token", max_length=255
                    ),
                ),
                ("scopes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
