services:
  - type: web
    name: toolkit-backend
    runtime: python
    buildCommand: "./config/build.sh"
    startCommand: "gunicorn --chdir src toolkit_backend.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
