# Generated by Django 5.2.6 on 2026-06-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScanLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scan_type",
                    models.CharField(
                        choices=[
                            ("url", "URL Scan"),
                            ("email", "Email Scan"),
                            ("metadata", "Metadata Fetch"),
                            ("spam", "Spam Detection"),
                        ],
                        max_length=20,
                    ),
                ),
                ("input_value", models.TextField()),
                ("result", models.TextField(blank=True, default="")),
                ("is_threat", models.BooleanField(default=False)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
