# Generated by Django 5.2.6 on 2026-06-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TakedownRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("malicious_url", models.URLField(max_length=2048)),
                ("description", models.TextField()),
                (
                    "screenshot",
                    models.ImageField(
                        blank=True, null=True, upload_to="takedown_screenshots/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("email_sent", "Email Sent to Host"),
                            ("resolved", "Website Removed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "hosting_provider",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "abuse_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("admin_notes", models.TextField(blank=True, default="")),
                ("email_body", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
