# Generated by Django 5.2.6 on 2026-07-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="author_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="question",
            name="author_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
    ]
